# Enable dynamic background opacity
dynamic_background_opacity yes

# Set background opacity (0.0 is fully transparent, 1.0 is fully opaque)
background_opacity 0.9
# Adjust this value as needed (e.g., 0.9 for more transparency)

# Optional: Enable background blur (if supported by your system)
background_blur 5 
# Adjust the blur radius as desired

# BEGIN_THEME

cursor #f5e0dc
cursor_text_color #f5e0dc
foreground #cdd6f4
background #1e1e2e
selection_foreground #1e1e2e
selection_background #cdd6f4
color0 #181825
color8 #585b70
color1 #f38ba8
color9 #f38ba8
color2 #a6e3a1
color10 #a6e3a1
color3 #f9e2af
color11 #f9e2af
color4 #89b4fa
color12 #89b4fa
color5 #cba6f7
color13 #cba6f7
color6 #94e2d5
color14 #94e2d5
color7 #bac2de
color15 #cdd6f4
url_color #94e2d5
active_border_color #89b4fa
inactive_border_color #585b70
bell_border_color #f9e2af
# END_THEME

# shell

shell zsh

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Mono"
font_size 14.0 
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

map ctrl+backspace send_text all \x17

clipboard_control write-clipboard write-primary no-append
